name: Error Form

description: |
  This report helps to declare errors (such as bad links, typos, ...).
  To avoid any confusion, please fill one report per error.

title: "[Error]: any_explicit_title" # mettre un titre clair

labels: ["invalid"] # ajouter un label

assignees: # assigner les membres de CONTEX
  - r3g31rk

      
body:
# ALREADY SEEN
  - type: checkboxes
    id: seen
    attributes:
      label: Are you the first one?
      description: Please check in this repo if an issue already exists for the error you spotted.
      options:
      - label: I searched the issues of this repo and no one exists for the error I spotted.
    validations:
      required: true

# WHERE
  - type: dropdown
    id: location_macro
    attributes:
      label: Error's macro location
      description: On which platform(s) did you spot the error?
      multiple: true
      options:
        - intra.epitech.digital (Gandalf) 
        - gandalf.epitech.eu (Merlin)
        - intra.epitech.eu (Intra)
        - jenkins.epitest.eu (Moulinette)
        - Github
    validations:
      required: true

  - type: textarea
    id: location_micro
    attributes:
      label: Error's micro location
      description: |
        What is the complete name, with extension, of the file where you spotted the error?
        (one filename per line if multiple files are impacted)
      placeholder: ex. D-POO-100_day01-exercices.pdf
    validations:
      required: true
      
# WHAT
  - type: input
    id: description
    attributes:
      label: Error's description
      description: Please give a clear and concise description of what you're experiencing. 
      placeholder: ex. Page 42, I read "pain au chocolat"
    validations:
      required: true
      
# HOW
  - type: textarea
    id: potential_fix
    attributes:
      label: What did you expect?
      description: Please give a clear and concise description of a potential fix.
      placeholder: ex. It should be "chocolatine".
    validations:
      required: false

  - type: textarea
    id: intell
    attributes:
      label: Anything else?
      description: |
        Links? Screenshots? References?
        Anything that provide more context about the error will help to fix it!
        Tip: You can attach images and files by clicking this area and then dragging files in.
    validations:
      required: false
      
  - type: input
    id: contact
    attributes:
      label: Contact details
      description: Except through github, how can we get in touch with you if we need more info?
      placeholder: ex. firstname.lastname@epitech.smthg
    validations:
      required: false





# WHY
  - type: markdown
    attributes:
      value: "## Thanks for taking the time to fill out this bug report! It will contribute to fix them and improve the pedagogical content."






  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell

