name: Error Form

description: |+
  This Form will declare an error (such as bad link, typo, wrong result,...) you have spotted.
  To avoid any confusion, please fill one report per error.

title: "[ERROR]: your_explicit_title" # mettre un titre clair

labels: ["invalid"] # ajouter un label

assignees: # assigner les membres de CONTEX
  - r3g31rk

body:
# ALREADY SEEN
  - type: checkboxes
    id: seen
    attributes:
      label: Are you the first one?
      description: Please check if an issue already exists for the error you spotted.
      options:
      - label: I have searched the open issues of this repo and no one exists for the error I spotted.
        required: true

# WHERE
  - type: dropdown
    id: location_macro
    attributes:
      label: Error's macro location
      description: On which platform(s) did you spot the error?
      multiple: true
      options:
        - intra.epitech.digital (Gandalf) 
        - gandalf.epitech.eu (Merlin)
        - intra.epitech.eu (Intra)
        - jenkins.epitest.eu (Moulinette)
        - Github
    validations:
      required: true

  - type: textarea
    id: location_micro
    attributes:
      label: Error's micro location
      description: >+
      What is the complete name of the file (with extension) where you spotted the error?
      
      (one per line if many file impacted)
      placeholder: ex. D-POO-100_day01-exercices.pdf
    validations:
      required: true
      
# WHAT
  - type: textarea
    id: description
    attributes:
      label: What did you see?
      description: Please give a clear and concise description of what you're experiencing. 
      placeholder: ex. Page 42, I read "pain au chocolat"

    validations:
      required: true
      
# HOW
  - type: textarea
    id: potential_fix
    attributes:
      label: What did you expect?
      description: Please give a clear and concise description of what you expected.
      placeholder: ex. It should be "chocolatine".
    validations:
      required: false

  - type: textarea
    id: intell
    attributes:
      label: Anything else?
      description: |
        Links? Screenshots? References? 
        Anything that will give us more context about the error you spotted will help us to solve it!

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
      
  - type: input
    id: contact
    attributes:
      label: Contact details
      description: Except through github, how can we get in touch with you if we need more info?
      placeholder: ex. firstname.lastname@epitech.eu
    validations:
      required: false


# WHY
        
  - type: markdown
    attributes:
      value: "### Thanks for taking the time to fill out this form! It will contribute to improve the quality of the pedagogical content delivered."




