name: Generate pdf
on:
  push:
    branches:
      - main
      - master
#    paths:
#      - '**.md'
  pull_request:
    branches:
      - main
      - master
    paths:
      - '**.md'
jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Link Checker
        uses: peter-evans/link-checker@v1.5.2
      - name: Create Issue From File
        uses: peter-evans/create-issue-from-file@v1.2.2
        with:
          title: Link Checker Report
          content-filepath: ./link-checker/out.md
          labels: report, automated issue
