name: Generate pdf
on:
  push:
    branches:
      - main
      - master
    paths:
      - '**.md'
  pull_request:
    branches:
      - main
      - master
    paths:
      - '**.md'
jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: gaurav-nelson/github-action-markdown-link-check@v1
    